[env]
TERM = "xterm-256color"

[window]
dimensions.lines = 35
dimensions.columns = 160
padding.x = 20
padding.y = 20
opacity = 0.75
blur = true

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal.family = "Fira Code"
size = 18

[cursor]
style.shape = "Beam"

[keyboard]

bindings = [
    # move-to by words
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    # move-to beginning/end of line
    { key = "Right", mods = "Command", chars = "\u0005" },
    { key = "Left", mods = "Command", chars = "\u0001" },
    # remove all text
    { key = "Back", mods = "Command", chars = "\u0015" },

]
